name: Build and Release Android App

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:

      # Build App

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Capacitor CLI
        run: npm install --save @capacitor/core @capacitor/cli @capacitor/android @capacitor/assets

      - name: Add Android platform
        run: npm exec cap add android

      - name: Generate Icons
        run: npm exec capacitor-assets generate --iconBackgroundColor "#FFFFFF"

      - name: Sync Capacitor
        run: npm exec cap sync android

      - name: Set up Android SDK and Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Build Android app
        env:
          ANDROID_HOME: $HOME/Android/Sdk
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          cd android && ./gradlew assembleDebug

      - name: Verify APK file
        run: |
          ls -lh android/app/build/outputs/apk/debug/

      # Release App

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./android/app/build/outputs/apk/debug/app-debug.apk
            ./android/app/build/outputs/apk/debug/output-metadata.json
